
name: uv-setup
description: Runs uv install and sync
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v6
    - name: Install uv
      uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
    - run: uv sync
      shell: bash
